#!/bin/bash
#SBATCH -J mil_uq_explain_mdsn
#SBATCH --nodes=1
#SBATCH --gres=gpu:A5000:1
#SBATCH --partition=A5000
#SBATCH --output=%x-%j.out
#SBATCH --error=%x-%j.err

# MD-SN HTML explanation wrapper for explain.py.
#
# Examples:
#   sbatch scripts/explain_slurm.sh
#   sbatch scripts/explain_slurm.sh dummy_data_es output/mdsn_train_123 output/mdsn_eval_123
#   sbatch scripts/explain_slurm.sh dummy_data_es output/mdsn_train_123 output/mdsn_eval_123 output/mdsn_eval_123/html 100 deferred_first
#
# Notes:
#   - This wrapper expects the artifacts generated by evaluate_slurm.sh (or an equivalent evaluate.py run).
#   - It calls explain.py, which renders the interactive HTML reports.

set -euo pipefail

if [ -n "${SLURM_SUBMIT_DIR:-}" ]; then
    SUBMIT_DIR=$(readlink -f "$SLURM_SUBMIT_DIR")
    if [ "$(basename "$SUBMIT_DIR")" = "scripts" ]; then
        PACKAGE_ROOT=$(readlink -f "$SUBMIT_DIR/..")
        DEFAULT_PROJECT_ROOT=$(readlink -f "$PACKAGE_ROOT/..")
    elif [ "$(basename "$SUBMIT_DIR")" = "mil_uq_public" ]; then
        PACKAGE_ROOT="$SUBMIT_DIR"
        DEFAULT_PROJECT_ROOT=$(readlink -f "$PACKAGE_ROOT/..")
    else
        DEFAULT_PROJECT_ROOT="$SUBMIT_DIR"
        PACKAGE_ROOT=$(readlink -f "$DEFAULT_PROJECT_ROOT/mil_uq_public")
    fi
else
    SCRIPT_DIR=$(readlink -f "$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)")
    PACKAGE_ROOT=$(readlink -f "$SCRIPT_DIR/..")
    DEFAULT_PROJECT_ROOT=$(readlink -f "$PACKAGE_ROOT/..")
fi

PROJECT_ROOT=$(readlink -f "${PROJECT_ROOT:-$DEFAULT_PROJECT_ROOT}")
LOG_DIR=$(readlink -f "${LOG_DIR:-$PACKAGE_ROOT/logs}")

DATASET_DIR=${1:-dummy_data_es}
MODEL_PATH=${2:-"$PACKAGE_ROOT/output/mdsn_train"}
EVAL_OUTPUT_DIR=${3:-"$PACKAGE_ROOT/output/mdsn_train/mdsn_eval"}
OUTPUT_DIR=${4:-"$EVAL_OUTPUT_DIR/html_${SLURM_JOB_ID:-manual}"}
N_EXAMPLES=${5:-25}
EXPLAIN_SELECT=${6:-deferred_first}
SEED=${7:-42}
EXTRA_ARGS=("${@:8}")

TEST_CSV=${TEST_CSV:-"$PACKAGE_ROOT/$DATASET_DIR/test.csv"}
PREDICTIONS_CSV=${PREDICTIONS_CSV:-""}
METRICS_JSON=${METRICS_JSON:-""}
CALIBRATION_BUNDLE=${CALIBRATION_BUNDLE:-""}
MAX_CHUNKS=${MAX_CHUNKS:-64}
ALL_INSTANCES=${ALL_INSTANCES:-0}
EXPLAIN_SCRIPT=${EXPLAIN_SCRIPT:-explain.py}

PYTHON_BIN_OVERRIDE=${PYTHON_BIN_OVERRIDE:-${PYTHON_BIN:-}}

export PYTHONUNBUFFERED=1
export TOKENIZERS_PARALLELISM=${TOKENIZERS_PARALLELISM:-false}
export OMP_NUM_THREADS=${OMP_NUM_THREADS:-1}

if [ ! -d "$MODEL_PATH" ]; then
    echo "[explain.mdsn] Missing model directory: $MODEL_PATH"
    exit 1
fi
if [ ! -f "$TEST_CSV" ]; then
    echo "[explain.mdsn] Missing test CSV: $TEST_CSV"
    exit 1
fi
if [ ! -f "$PACKAGE_ROOT/$EXPLAIN_SCRIPT" ]; then
    echo "[explain.mdsn] Missing explainer entrypoint: $PACKAGE_ROOT/$EXPLAIN_SCRIPT"
    exit 1
fi
if [ -z "$PREDICTIONS_CSV" ] && [ -z "$METRICS_JSON" ] && [ -z "$CALIBRATION_BUNDLE" ] && [ ! -d "$EVAL_OUTPUT_DIR" ]; then
    echo "[explain.mdsn] Missing eval output directory: $EVAL_OUTPUT_DIR"
    echo "[explain.mdsn] Provide EVAL_OUTPUT_DIR or explicit PREDICTIONS_CSV/METRICS_JSON/CALIBRATION_BUNDLE overrides."
    exit 1
fi

if [ -n "$PYTHON_BIN_OVERRIDE" ]; then
    if [ ! -x "$PYTHON_BIN_OVERRIDE" ]; then
        echo "[explain.mdsn] Python override is not executable: $PYTHON_BIN_OVERRIDE"
        exit 1
    fi
    PYTHON_BIN="$PYTHON_BIN_OVERRIDE"
elif command -v python >/dev/null 2>&1; then
    PYTHON_BIN=$(command -v python)
elif command -v python3 >/dev/null 2>&1; then
    PYTHON_BIN=$(command -v python3)
else
    echo "[explain.mdsn] Could not find a Python interpreter."
    exit 1
fi

mkdir -p "$PACKAGE_ROOT/output"
mkdir -p "$LOG_DIR"

echo "[explain.mdsn] Job ID: ${SLURM_JOB_ID:-local}"
echo "[explain.mdsn] Package root: $PACKAGE_ROOT"
echo "[explain.mdsn] Project root: $PROJECT_ROOT"
echo "[explain.mdsn] Python: $PYTHON_BIN"
echo "[explain.mdsn] Dataset dir: $DATASET_DIR"
echo "[explain.mdsn] Test CSV: $TEST_CSV"
echo "[explain.mdsn] Model path: $MODEL_PATH"
echo "[explain.mdsn] Eval output dir: $EVAL_OUTPUT_DIR"
echo "[explain.mdsn] Output dir: $OUTPUT_DIR"
echo "[explain.mdsn] n_examples: $N_EXAMPLES"
echo "[explain.mdsn] explain_select: $EXPLAIN_SELECT"
echo "[explain.mdsn] max_chunks: $MAX_CHUNKS"
echo "[explain.mdsn] seed: $SEED"
echo ""

cd "$PACKAGE_ROOT"

CMD=(
    "$PYTHON_BIN" "$EXPLAIN_SCRIPT"
    --model_path "$MODEL_PATH"
    --test_csv "$TEST_CSV"
    --output_dir "$OUTPUT_DIR"
    --eval_output_dir "$EVAL_OUTPUT_DIR"
    --n_examples "$N_EXAMPLES"
    --explain_select "$EXPLAIN_SELECT"
    --max_chunks "$MAX_CHUNKS"
    --seed "$SEED"
)

if [ -n "$PREDICTIONS_CSV" ]; then
    CMD+=(--predictions_csv "$PREDICTIONS_CSV")
fi
if [ -n "$METRICS_JSON" ]; then
    CMD+=(--metrics_json "$METRICS_JSON")
fi
if [ -n "$CALIBRATION_BUNDLE" ]; then
    CMD+=(--calibration_bundle "$CALIBRATION_BUNDLE")
fi
if [ "$ALL_INSTANCES" = "1" ]; then
    CMD+=(--all_instances)
fi
if [ ${#EXTRA_ARGS[@]} -gt 0 ]; then
    CMD+=("${EXTRA_ARGS[@]}")
fi

echo "[explain.mdsn] Launch command: ${CMD[*]}"
echo ""

if [ -n "${SLURM_JOB_ID:-}" ] && command -v srun >/dev/null 2>&1; then
    srun --unbuffered "${CMD[@]}"
else
    "${CMD[@]}"
fi

echo ""
echo "[explain.mdsn] Explanation generation completed successfully."